"use client";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { createPublicClient, http } from "viem";
import { goerli } from "viem/chains";
import { WagmiConfig, createConfig } from "wagmi";
import { AxiomProvider } from "./_service/Axiom/AxiomProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const config = createConfig({
  autoConnect: true,
  publicClient: createPublicClient({
    chain: goerli,
    transport: http(),
  }),
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WagmiConfig config={config}>
          <AxiomProvider
            config={{
              providerUri: "",
              version: "experimental",
              chainId: 5,
              mock: true,
            }}
          >
            {children}
          </AxiomProvider>
        </WagmiConfig>
      </body>
    </html>
  );
}
